DoeETransforme/HelpU

- src/main/java/br/senac/helpu/modelo/entidade/usuario/Usuario.java
Adicionei o mappedBy para a classe Conquista
> Alterada a classe Usuario

- src/main/java/br/senac/helpu/modelo/dao/propostadoacao/PropostaDoacaoDAOImpl.java
- src/main/java/br/senac/helpu/modelo/entidade/alimento/Alimento.java
- src/main/java/br/senac/helpu/modelo/entidade/item/Item.java
Alterado Mapeamento da Classe Item
> Alterado Mapeamento da Classe Item

- src/main/java/br/senac/helpu/modelo/entidade/propostadoacao/PropostaDoacao.java
Arrumei o relacionamento de PropostaDoacao com PedidoDoacao de N - N, para N propostas -  1 pedido
> Atualizado o mapeamento da classe PropostaDoacao

- src/main/java/br/senac/helpu/modelo/entidade/pedidodoacao/PedidoDoacao.java
Arrumei o relacionamento de PedidoDoacao com PropostaDoacao
> Atualizado o mapeamento da classe PedidoDoacao

- src/main/java/br/senac/helpu/modelo/entidade/doador/Doador.java
- src/main/java/br/senac/helpu/modelo/entidade/usuario/Usuario.java
Trocado o atributo de List<conquistas> da classe usuario para a classe de doador
> Alterado a classe Usuario e Doador

- src/main/java/br/senac/helpu/modelo/entidade/alimento/Alimento.java
Alterado Mapeamento da Classe Alimento
> Alterado Mapeamento da Classe Alimento

- src/main/java/br/senac/helpu/modelo/dao/alimento/AlimentoDAOImpl.java
Estava errado o fechamento do bloco
> Alterado o DAO da classe Alimento

- src/main/java/br/senac/helpu/modelo/entidade/item/Item.java
Foi inserido metodos getters and setters para pedidodoacao e propostadoacao
> Atualizado a classe Item

- src/main/java/br/senac/helpu/modelo/entidade/pedidodoacao/PedidoDoacao.java
> Alterada Classe PedidoDoacao

- src/main/java/br/senac/helpu/modelo/dao/contato/ContatoDAOimpl.java
- src/main/java/br/senac/helpu/modelo/dao/doador/DoadorDAOimpl.java
- src/main/java/br/senac/helpu/modelo/dao/ong/OngDAOimpl.java
> Alterado o DAO da classe Ong

- src/main/java/br/senac/helpu/modelo/entidade/ong/Ong.java
Alterado Mapeamento Classe Ong
> Alterado Mapeamento Classe Ong

- src/main/java/br/senac/helpu/Main.java
- src/main/java/br/senac/helpu/modelo/entidade/contato/Contato.java
> Alterada Classe Contato

- src/main/java/br/senac/helpu/Main.java
- src/main/java/br/senac/helpu/modelo/entidade/propostadoacao/PropostaDoacao.java
Proposta doacao agora esta inserindo
> Alterado a classe prospotaDoacao

- src/main/java/br/senac/helpu/Main.java
- src/main/java/br/senac/helpu/modelo/entidade/propostadoacao/PropostaDoacao.java
Corrigido erro no construtor, e mapeamento.
> Alterada Classe PropostaDoacao

- src/main/java/br/senac/helpu/Main.java
- src/main/java/br/senac/helpu/modelo/entidade/endereco/Endereco.java
- src/main/java/br/senac/helpu/modelo/entidade/ong/Ong.java
Foi alterado o mapeamento entre as classes endereço e ong.
> Alterado Mapeamento da Classe Endereco

- src/main/java/br/senac/helpu/modelo/entidade/usuario/Usuario.java
> Atualizado o mapeamento da classe usuário

- src/main/java/br/senac/helpu/modelo/dao/propostadoacao/PropostaDoacaoDAOImpl.java
- src/main/java/br/senac/helpu/modelo/entidade/propostadoacao/PropostaDoacao.java
As consultas com ong agora estão dando certo, porém ainda tem algumas com erro
> Atualizado o DAO da classe PropostaDoacao

- src/main/java/br/senac/helpu/modelo/entidade/pedidodoacao/PedidoDoacao.java
Foi adicionado metodos de inserir e remover elemento das listas itens e propostasdoacao que estava faltando
> Atualizado a classe PedidoDoacao

- src/main/webapp/resources/paginas/Cadastro_PF.jsp
> Alterado Cadastro_PF

- pom.xml
- src/main/webapp/resources/paginas/Cadastro_PF.jsp
> Alterado Formulario Doador

- src/main/webapp/index.jsp
- src/main/webapp/resources/paginas/cadastro-doador.jsp
Alterado o link do index em direciona para o doador
> Alterado Index

- src/main/java/br/senac/helpu/controle/servlet/Servlet.java
- src/main/java/br/senac/helpu/modelo/dao/usuario/UsuarioDAOImpl.java
- src/main/java/br/senac/helpu/modelo/entidade/contato/Contato.java
- src/main/java/br/senac/helpu/modelo/entidade/doador/Doador.java
- src/main/java/br/senac/helpu/modelo/entidade/usuario/Usuario.java
- src/main/webapp/resources/paginas/cadastro-doador.jsp
Corrigido erro no DAO  erro em que duplicava os inserts, também foram  corrigidos erros menores
> Alterado Cadastro Doador

- src/main/java/br/senac/helpu/modelo/dao/conquista/ConquistaDAOImpl.java
Removido colchetes que estava  causando erro.
> Alterado DAO da Classe Conquista

- src/main/java/br/senac/helpu/modelo/entidade/endereco/Endereco.java
Arrumei os construtores da classe endereco
> Atualizado a classe Endereco

- src/main/webapp/resources/paginas/editar-pedido.jsp
- src/main/webapp/resources/paginas/editar-perfil-doador.jsp
- src/main/webapp/resources/paginas/editar-perfil-ong.jsp
- src/main/webapp/resources/paginas/excluir-conta-doador.jsp
Arrumado os editar e deletar do jsp
> Atualizado Editar Pedido

- src/main/java/br/senac/helpu/Main.java
- src/main/java/br/senac/helpu/controle/servlet/Servlet.java
- src/main/java/br/senac/helpu/modelo/dao/item/ItemDAO.java
- src/main/java/br/senac/helpu/modelo/dao/item/ItemDAOImpl.java
- src/main/java/br/senac/helpu/modelo/entidade/item/Item.java
- src/main/webapp/resources/paginas/cadastro-item.jsp
- src/main/webapp/resources/paginas/cadastro-ongsegundo.jsp
Foi criado o request no servlet necessário para cadastrar Item foram feitas outras alterações para correção de erros e alteração no alimento para puxar o objeto alimento.
> Criado Servlet Cadastro Item

- src/main/java/br/senac/helpu/modelo/dao/usuario/UsuarioDAO.java
- src/main/java/br/senac/helpu/modelo/dao/usuario/UsuarioDAOImpl.java
Criado os metodos de login em usuario
> Atualizado o DAO da classe Usuario

- src/main/java/br/senac/helpu/controle/servlet/Servlet.java
- src/main/java/br/senac/helpu/modelo/dao/alimento/AlimentoDAO.java
- src/main/java/br/senac/helpu/modelo/dao/alimento/AlimentoDAOImpl.java
- src/main/webapp/resources/paginas/cadastro-item.jsp
- src/main/webapp/resources/paginas/cadastro-pedido.jsp
Criado inserir item, modificado o mostrar cadastro item e alterado html.
> Criado Inserir Item

- src/main/java/br/senac/helpu/controle/servlet/Servlet.java
- src/main/java/br/senac/helpu/modelo/dao/contato/ContatoDAO.java
- src/main/java/br/senac/helpu/modelo/dao/contato/ContatoDAOImpl.java
- src/main/webapp/resources/paginas/editar-perfil-doador.jsp
> Criado o editar doador

- src/main/java/br/senac/helpu/controle/servlet/Servlet.java
- src/main/java/br/senac/helpu/modelo/dao/propostadoacao/PropostaDoacaoDAO.java
- src/main/java/br/senac/helpu/modelo/dao/propostadoacao/PropostaDoacaoDAOImpl.java
- src/main/java/br/senac/helpu/modelo/entidade/doador/Doador.java
- src/main/webapp/resources/paginas/historico-doacoes.jsp
agora é possivel recuperar o historico de daacoes
> Alterado historico-doacoes

- src/main/java/br/senac/helpu/controle/servlet/Servlet.java
- src/main/webapp/resources/paginas/editar-perfil-doador.jsp
Foram adicionados inputs que estavam faltando assim como no servlet, que estavam levando o código a quebrar por conta do construtor
> Alterado Editar Doador

- src/main/java/br/senac/helpu/controle/servlet/Servlet.java
- src/main/java/br/senac/helpu/modelo/entidade/pedidodoacao/PedidoDoacao.java
Arrumado inserir pedido, houve alteração no mapeamento sendo obrigatório a ligação com ong, a partir disso foi inserido o id da ong no serlvet.
> Alterado Cadastro Pedido

- src/main/java/br/senac/helpu/controle/servlet/Servlet.java
- src/main/webapp/resources/paginas/cadastro-proposta.jsp
Agora o inserir proposta esta pegando pelo session
> Atualizado o inserir Proposta

- src/main/java/br/senac/helpu/controle/servlet/Servlet.java
- src/main/webapp/resources/paginas/perfil-ong.jsp
esta aparecendo agora as informações na tela da ong
> Atualizado o perfil ong no jsp

- src/main/java/br/senac/helpu/controle/servlet/Servlet.java
- src/main/java/br/senac/helpu/modelo/entidade/pedidodoacao/PedidoDoacao.java
- src/main/webapp/resources/paginas/cadastro-pedido.jsp
- src/main/webapp/resources/paginas/historico-pedidos.jsp
criado o meta de doações e agora está funcionando o pedido que for inserido aparecer na tela
> Atualizado o historico de pedidos

- src/main/java/br/senac/helpu/controle/servlet/Servlet.java
- src/main/java/br/senac/helpu/modelo/dao/propostadoacao/PropostaDoacaoDAO.java
- src/main/java/br/senac/helpu/modelo/dao/propostadoacao/PropostaDoacaoDAOImpl.java
- src/main/java/br/senac/helpu/modelo/entidade/item/Item.java
- src/main/java/br/senac/helpu/modelo/entidade/propostadoacao/PropostaDoacao.java
- src/main/webapp/resources/paginas/descricao-proposta.jsp
- src/main/webapp/resources/paginas/menu.jsp
- src/main/webapp/resources/paginas/propostas-pendentes.jsp
Criado a paginas descricao-proposta, feito e corrigido consultas e corrigido jsp.
> Alterado Propostas Pendentes

- src/main/java/br/senac/helpu/controle/servlet/Servlet.java
- src/main/java/br/senac/helpu/modelo/dao/propostadoacao/PropostaDoacaoDAO.java
- src/main/java/br/senac/helpu/modelo/dao/propostadoacao/PropostaDoacaoDAOImpl.java
- src/main/webapp/resources/paginas/descricao-pedido.jsp
- src/main/webapp/resources/paginas/perfil-ong.jsp
Foi alterado a descrição  pedido e perfil Ong para que as informações do pedido correspondente sejam devidamente informadas.
> Alterado Descricao de Pedido

- src/main/java/br/senac/helpu/controle/servlet/Servlet.java
- src/main/java/br/senac/helpu/modelo/dao/propostadoacao/PropostaDoacaoDAO.java
- src/main/java/br/senac/helpu/modelo/dao/propostadoacao/PropostaDoacaoDAOImpl.java
- src/main/webapp/resources/paginas/cadastro-ong.jsp
- src/main/webapp/resources/paginas/perfil-doador.jsp
Foi criado a consulta e foi feito um foreach para recuperar um limite de 3 propostas efetuadas e organizadas pela ordem da data de criação.
> Alterado Perfil Doador

- src/main/java/br/senac/helpu/controle/servlet/Servlet.java
- src/main/java/br/senac/helpu/modelo/dao/propostadoacao/PropostaDoacaoDAO.java
- src/main/java/br/senac/helpu/modelo/dao/propostadoacao/PropostaDoacaoDAOImpl.java
- src/main/webapp/resources/paginas/avaliar-proposta.jsp
- src/main/webapp/resources/paginas/descricao-proposta.jsp
- src/main/webapp/resources/paginas/propostas-analise.jsp
Falta exibir contato, não consegui que a consulta puxa-se as informações
> Alterado Avaliar Proposta

- src/main/webapp/resources/css/propostas-pendentes.css
- src/main/webapp/resources/paginas/propostas-pendentes.jsp
Foi alterado o html do propostas pendentes, criado o css correspondente para a pagina e ajustado.
> Alterado CSS do Propostas Pendentes

- src/main/webapp/resources/paginas/esqueci-minha-senha.jsp
- src/main/webapp/resources/paginas/resultado-pesquisa.jsp
Feitas algumas correções de alguns erros que estavam causando o mau funcionamento do mesmo.
> Alterado Menu

- src/main/webapp/resources/css/descricao-pedido.css
- src/main/webapp/resources/paginas/descricao-pedido.jsp
- src/main/webapp/resources/paginas/descricao-proposta.jsp
Terminando Descrição Pedido, feito alguns alinhamentos
> Alterado Descrição Pedido

- src/main/java/br/senac/helpu/controle/servlet/Servlet.java
- src/main/java/br/senac/helpu/modelo/dao/propostadoacao/PropostaDoacaoDAO.java
- src/main/java/br/senac/helpu/modelo/dao/propostadoacao/PropostaDoacaoDAOImpl.java
- src/main/webapp/resources/css/descricao-proposta.css
- src/main/webapp/resources/css/estilo.css
- src/main/webapp/resources/css/excluir-proposta.css
- src/main/webapp/resources/css/historico-doacoes.css
- src/main/webapp/resources/css/login.css
- src/main/webapp/resources/paginas/descricao-pedido.jsp
- src/main/webapp/resources/paginas/descricao-proposta.jsp
- src/main/webapp/resources/paginas/editar-proposta.jsp
- src/main/webapp/resources/paginas/excluir-proposta.jsp
- src/main/webapp/resources/paginas/historico-doacoes.jsp
- src/main/webapp/resources/paginas/perfil-doador.jsp
- src/main/webapp/resources/paginas/proposta-excluida.jsp
- src/main/webapp/resources/paginas/propostas-pendentes.jsp
Alterado histórico de doações, também foi alterado todos as paginas que possuem card, também foi ajustado e alterado descrição proposta assim como editar proposta e excluir proposta
> Alterado Historico de Doacoes

- src/main/webapp/resources/css/historico-pedidos.css
- src/main/webapp/resources/paginas/descricao-pedido.jsp
- src/main/webapp/resources/paginas/historico-pedidos.jsp
Alterado os cards do Histórico de Pedidos
> Alterado Historico Pedidos

- src/main/java/br/senac/helpu/controle/servlet/Servlet.java
- src/main/java/br/senac/helpu/modelo/dao/pedidodoacao/PedidoDoacaoDAOImpl.java
- src/main/webapp/index.jsp
- src/main/webapp/resources/css/historico-doacoes.css
- src/main/webapp/resources/css/historico-pedidos.css
- src/main/webapp/resources/css/index.css
- src/main/webapp/resources/css/perfil-doador.css
- src/main/webapp/resources/css/propostas-pendentes.css
- src/main/webapp/resources/css/resultado-pesquisa.css
Diversos cards foram ajustados para funcionarem melhor nos notebooks
> Alterado Diversos cards
